// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdy9KclD_uJXOmiXee-pCj83E7Lv8Sok4',
    appId: '1:1001399130333:web:e376b0c6e3b8090b582334',
    messagingSenderId: '1001399130333',
    projectId: 'med-reminder-app-c5658',
    authDomain: 'med-reminder-app-c5658.firebaseapp.com',
    storageBucket: 'med-reminder-app-c5658.firebasestorage.app',
    measurementId: 'G-PL54RBJBV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFtPVq1QQ2m5gIHoORTK_3hkZD4YKQags',
    appId: '1:1001399130333:android:3ce8ad057805e7f2582334',
    messagingSenderId: '1001399130333',
    projectId: 'med-reminder-app-c5658',
    storageBucket: 'med-reminder-app-c5658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIiK7obglSKRGfoC9bp1SZwnc2W4hqqM',
    appId: '1:1001399130333:ios:6b7c6716ad536890582334',
    messagingSenderId: '1001399130333',
    projectId: 'med-reminder-app-c5658',
    storageBucket: 'med-reminder-app-c5658.firebasestorage.app',
    iosBundleId: 'com.example.medReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvIiK7obglSKRGfoC9bp1SZwnc2W4hqqM',
    appId: '1:1001399130333:ios:6b7c6716ad536890582334',
    messagingSenderId: '1001399130333',
    projectId: 'med-reminder-app-c5658',
    storageBucket: 'med-reminder-app-c5658.firebasestorage.app',
    iosBundleId: 'com.example.medReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdy9KclD_uJXOmiXee-pCj83E7Lv8Sok4',
    appId: '1:1001399130333:web:4eeeb8fc88a0666a582334',
    messagingSenderId: '1001399130333',
    projectId: 'med-reminder-app-c5658',
    authDomain: 'med-reminder-app-c5658.firebaseapp.com',
    storageBucket: 'med-reminder-app-c5658.firebasestorage.app',
    measurementId: 'G-DQXMEVQ0X2',
  );
}
